// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzkvfhptnrdvazxsryqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6a3ZmaHB0bnJkdmF6eHNyeXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzIwMzIsImV4cCI6MjA2MDk0ODAzMn0._uACfEpro71SjiJvS3d-mTQacIO9XFEClb1d4ThxF-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);